kind = "mobile"
previewPath = "/ryzer-app/"
title = "Ryzer App"
version = "1.0.0"
id = "artifacts/ryzer-app"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/ryzer-app/" ]
localPort = 22479

[services.development]
run = "pnpm --filter @workspace/ryzer-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ryzer-app", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/ryzer-app", "run", "serve" ]

[services.env]
PORT = "22479"
BASE_PATH = "/ryzer-app/"
